# Generated by Django 2.2.9 on 2020-01-21 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_works_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='specialist_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to='category.Specialist'),
        ),
    ]
