# Generated by Django 2.2.9 on 2020-01-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20200121_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
