# Generated by Django 2.2.9 on 2020-01-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20200121_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changelog',
            old_name='count',
            new_name='value',
        ),
    ]
