# Generated by Django 2.2.9 on 2020-02-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20200201_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='works',
            new_name='services',
        ),
        migrations.RenameField(
            model_name='works',
            old_name='duration',
            new_name='hours',
        ),
        migrations.RemoveField(
            model_name='works',
            name='number',
        ),
    ]
