# Generated by Django 2.2.9 on 2020-02-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20200202_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
