# Generated by Django 2.2.9 on 2020-02-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_works_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='works',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='category',
            name='services',
            field=models.ManyToManyField(related_name='services', to='category.Works'),
        ),
    ]
