# Generated by Django 2.2.9 on 2020-03-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_auto_20200202_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isOriginal',
            field=models.BooleanField(default=True),
        ),
    ]
