# Generated by Django 2.2.9 on 2020-03-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_auto_20200317_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='hours',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
