# Generated by Django 2.2.9 on 2020-03-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_auto_20200317_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, null=True),
        ),
    ]
