# Generated by Django 4.2.7 on 2023-12-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_auto_20200318_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='isOriginal',
            field=models.BooleanField(default=True, verbose_name='Оригинальная работа'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='services',
            field=models.ManyToManyField(related_name='services', to='category.works', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='rate',
            field=models.FloatField(default=1, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='works',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='works',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, null=True, verbose_name='Часы'),
        ),
        migrations.AlterField(
            model_name='works',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='works',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='works',
            name='specialist_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_type', to='category.specialist', verbose_name='Тип специалиста'),
        ),
    ]
